// Человеко-читаемый перевод технических server-error строк.
// Сервер шлёт короткие английские коды вроде "wrong phase", "not enough cash".
// Мапим их в RU/EN понятные фразы. Если кода нет в словаре — показываем как есть.

type Locale = "ru" | "en";

const DICT_RU: Record<string, string> = {
  "no player": "Игрок не найден",
  "not in jail": "Ты не в тюрьме",
  "not your turn": "Сейчас не твой ход",
  "wrong phase": "Сейчас не то время для этого действия",
  "not enough cash": "Недостаточно денег",
  "no jail card": "Нет карты освобождения",
  "not a street": "Это не улица",
  "not your property": "Это не твоя собственность",
  "mortgaged": "Участок заложен",
  "hotel already": "Отель уже построен",
  "need monopoly": "Нужна монополия (все участки цвета)",
  "build evenly": "Строй равномерно по группе",
  "sell evenly": "Продавай равномерно",
  "nothing to sell": "Нечего продавать",
  "not property": "Нельзя заложить эту клетку",
  "already mortgaged": "Уже заложено",
  "sell buildings first": "Сначала продай постройки",
  "not mortgaged": "Не в залоге",
  "not in game": "Игра ещё не началась",
  "a trade is already pending": "Обмен уже в процессе",
  "no buyer": "Покупатель недоступен",
  "nobody owns this": "Клетка ничья",
  "already yours": "Уже твоё",
  "sell houses first": "Сначала продай дома",
  "no pending trade": "Нет активного обмена",
  "not your offer": "Обмен адресован не тебе",
  "trade invalid": "Обмен больше невозможен",
  "buyer no longer has cash": "У покупателя не хватает денег",
  "cannot trade with yourself": "Нельзя обмениваться с собой",
  "bankrupt player": "Игрок банкрот",
  "empty trade": "Пустой обмен — добавь хотя бы одно",
  "tile on both sides": "Один и тот же участок не может быть с двух сторон",
  "recipient lacks cash": "У получателя не хватает денег",
  "not enough jail cards": "Не хватает карт «выйти из тюрьмы»",
  "recipient lacks jail cards": "У получателя нет карт «выйти из тюрьмы»",
  "you don't own a tile": "Ты не владеешь этим участком",
  "they don't own a tile": "Получатель не владеет этим участком",
  "sell buildings on the colour group first": "Сначала продай постройки в этой цветовой группе",
  "their colour group has buildings": "В цветовой группе получателя есть постройки",
  "your colour group now has buildings — sell them first": "В твоей группе появились постройки — продай их",
  "initiator no longer has cash": "У инициатора больше нет денег",
  "recipient no longer has cash": "У получателя больше нет денег",
  "initiator no longer has jail cards": "У инициатора нет карт «выйти из тюрьмы»",
  "recipient no longer has jail cards": "У получателя нет карт «выйти из тюрьмы»",
  "tile unavailable": "Участок недоступен",
  "initiator can't cover trade + mortgage interest": "Инициатор не может оплатить процент по залогу",
  "recipient can't cover trade + mortgage interest": "Получатель не может оплатить процент по залогу",
  "no auction": "Аукцион не идёт",
  "bankrupt": "Игрок банкрот",
  "passed": "Ты уже пасанул",
  "bad amount": "Неверная сумма",
  "bid too low": "Ставка слишком мала",
  "room not found": "Комната закрыта или не существует",
  "not host": "Только хост может это сделать",
};

const DICT_EN: Record<string, string> = {
  "no player": "Player not found",
  "not in jail": "You're not in jail",
  "not your turn": "It's not your turn",
  "wrong phase": "Can't do this right now",
  "not enough cash": "Not enough cash",
  "no jail card": "No Get-Out-of-Jail card",
  "not a street": "Not a street tile",
  "not your property": "Not your property",
  "mortgaged": "Property is mortgaged",
  "hotel already": "Hotel already built",
  "need monopoly": "Need the full color set",
  "build evenly": "Build evenly across the set",
  "sell evenly": "Sell evenly across the set",
  "nothing to sell": "Nothing to sell",
  "not property": "Can't mortgage this tile",
  "already mortgaged": "Already mortgaged",
  "sell buildings first": "Sell buildings first",
  "not mortgaged": "Not mortgaged",
  "not in game": "Game hasn't started",
  "a trade is already pending": "A trade is already pending",
  "no buyer": "Buyer unavailable",
  "nobody owns this": "Nobody owns this",
  "already yours": "Already yours",
  "sell houses first": "Sell houses first",
  "no pending trade": "No pending trade",
  "not your offer": "Offer is not addressed to you",
  "trade invalid": "Trade no longer valid",
  "buyer no longer has cash": "Buyer is short on cash",
  "cannot trade with yourself": "Can't trade with yourself",
  "bankrupt player": "Player is bankrupt",
  "empty trade": "Empty offer — add at least one item",
  "tile on both sides": "Same tile can't be on both sides",
  "recipient lacks cash": "Recipient is short on cash",
  "not enough jail cards": "Not enough Get-Out cards",
  "recipient lacks jail cards": "Recipient lacks Get-Out cards",
  "you don't own a tile": "You don't own that tile",
  "they don't own a tile": "Recipient doesn't own that tile",
  "sell buildings on the colour group first": "Sell buildings on that colour group first",
  "their colour group has buildings": "Recipient's colour group has buildings",
  "your colour group now has buildings — sell them first": "Your colour group now has buildings — sell them first",
  "initiator no longer has cash": "Initiator no longer has cash",
  "recipient no longer has cash": "Recipient no longer has cash",
  "initiator no longer has jail cards": "Initiator no longer has Get-Out cards",
  "recipient no longer has jail cards": "Recipient no longer has Get-Out cards",
  "tile unavailable": "Tile unavailable",
  "initiator can't cover trade + mortgage interest": "Initiator can't cover mortgage interest",
  "recipient can't cover trade + mortgage interest": "Recipient can't cover mortgage interest",
  "no auction": "No auction running",
  "bankrupt": "Player is bankrupt",
  "passed": "You already passed",
  "bad amount": "Bad amount",
  "bid too low": "Bid too low",
  "room not found": "Room is closed or gone",
  "not host": "Only the host can do that",
};

export function humanError(raw: string | null | undefined, locale: Locale | string): string {
  if (!raw) return "";
  const dict = locale === "ru" ? DICT_RU : DICT_EN;
  return dict[raw] ?? raw;
}
