import type { Tile } from "./types";

/**
 * Классическая доска Монополии Hasbro Atlantic City (40 клеток).
 * Названия даны на английском и русском — UI показывает по локали.
 * Цены / аренда / стоимость домов — из оригинальных правил.
 */
export const BOARD: Tile[] = [
  { kind: "go", index: 0, name: { en: "GO", ru: "СТАРТ" } },
  {
    kind: "street",
    index: 1,
    name: { en: "Mediterranean Avenue", ru: "Средиземноморский пр." },
    group: "brown",
    price: 60,
    rent: [2, 10, 30, 90, 160, 250],
    houseCost: 50,
    mortgage: 30,
  },
  { kind: "chest", index: 2, name: { en: "Community Chest", ru: "Казна" } },
  {
    kind: "street",
    index: 3,
    name: { en: "Baltic Avenue", ru: "Балтийский пр." },
    group: "brown",
    price: 60,
    rent: [4, 20, 60, 180, 320, 450],
    houseCost: 50,
    mortgage: 30,
  },
  { kind: "tax", index: 4, name: { en: "Income Tax", ru: "Подоходный налог" }, amount: 200 },
  {
    kind: "railroad",
    index: 5,
    name: { en: "Reading Railroad", ru: "Рединг" },
    price: 200,
    mortgage: 100,
  },
  {
    kind: "street",
    index: 6,
    name: { en: "Oriental Avenue", ru: "Восточный пр." },
    group: "lightBlue",
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgage: 50,
  },
  { kind: "chance", index: 7, name: { en: "Chance", ru: "Шанс" } },
  {
    kind: "street",
    index: 8,
    name: { en: "Vermont Avenue", ru: "Вермонтский пр." },
    group: "lightBlue",
    price: 100,
    rent: [6, 30, 90, 270, 400, 550],
    houseCost: 50,
    mortgage: 50,
  },
  {
    kind: "street",
    index: 9,
    name: { en: "Connecticut Avenue", ru: "Коннектикутский пр." },
    group: "lightBlue",
    price: 120,
    rent: [8, 40, 100, 300, 450, 600],
    houseCost: 50,
    mortgage: 60,
  },
  { kind: "jail", index: 10, name: { en: "Jail / Just Visiting", ru: "Тюрьма / В гостях" } },
  {
    kind: "street",
    index: 11,
    name: { en: "St. Charles Place", ru: "Сент-Чарлз Плейс" },
    group: "pink",
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgage: 70,
  },
  {
    kind: "utility",
    index: 12,
    name: { en: "Electric Company", ru: "Электростанция" },
    price: 150,
    mortgage: 75,
  },
  {
    kind: "street",
    index: 13,
    name: { en: "States Avenue", ru: "Стейтс-авеню" },
    group: "pink",
    price: 140,
    rent: [10, 50, 150, 450, 625, 750],
    houseCost: 100,
    mortgage: 70,
  },
  {
    kind: "street",
    index: 14,
    name: { en: "Virginia Avenue", ru: "Виргинский пр." },
    group: "pink",
    price: 160,
    rent: [12, 60, 180, 500, 700, 900],
    houseCost: 100,
    mortgage: 80,
  },
  {
    kind: "railroad",
    index: 15,
    name: { en: "Pennsylvania Railroad", ru: "Пенсильвания" },
    price: 200,
    mortgage: 100,
  },
  {
    kind: "street",
    index: 16,
    name: { en: "St. James Place", ru: "Сент-Джеймс Плейс" },
    group: "orange",
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgage: 90,
  },
  { kind: "chest", index: 17, name: { en: "Community Chest", ru: "Казна" } },
  {
    kind: "street",
    index: 18,
    name: { en: "Tennessee Avenue", ru: "Теннесси-авеню" },
    group: "orange",
    price: 180,
    rent: [14, 70, 200, 550, 750, 950],
    houseCost: 100,
    mortgage: 90,
  },
  {
    kind: "street",
    index: 19,
    name: { en: "New York Avenue", ru: "Нью-Йорк-авеню" },
    group: "orange",
    price: 200,
    rent: [16, 80, 220, 600, 800, 1000],
    houseCost: 100,
    mortgage: 100,
  },
  { kind: "freeParking", index: 20, name: { en: "Free Parking", ru: "Бесплатная парковка" } },
  {
    kind: "street",
    index: 21,
    name: { en: "Kentucky Avenue", ru: "Кентукки-авеню" },
    group: "red",
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgage: 110,
  },
  { kind: "chance", index: 22, name: { en: "Chance", ru: "Шанс" } },
  {
    kind: "street",
    index: 23,
    name: { en: "Indiana Avenue", ru: "Индиана-авеню" },
    group: "red",
    price: 220,
    rent: [18, 90, 250, 700, 875, 1050],
    houseCost: 150,
    mortgage: 110,
  },
  {
    kind: "street",
    index: 24,
    name: { en: "Illinois Avenue", ru: "Иллинойс-авеню" },
    group: "red",
    price: 240,
    rent: [20, 100, 300, 750, 925, 1100],
    houseCost: 150,
    mortgage: 120,
  },
  {
    kind: "railroad",
    index: 25,
    name: { en: "B&O Railroad", ru: "Балтимор-Огайо" },
    price: 200,
    mortgage: 100,
  },
  {
    kind: "street",
    index: 26,
    name: { en: "Atlantic Avenue", ru: "Атлантик-авеню" },
    group: "yellow",
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgage: 130,
  },
  {
    kind: "street",
    index: 27,
    name: { en: "Ventnor Avenue", ru: "Вентнор-авеню" },
    group: "yellow",
    price: 260,
    rent: [22, 110, 330, 800, 975, 1150],
    houseCost: 150,
    mortgage: 130,
  },
  {
    kind: "utility",
    index: 28,
    name: { en: "Water Works", ru: "Водоканал" },
    price: 150,
    mortgage: 75,
  },
  {
    kind: "street",
    index: 29,
    name: { en: "Marvin Gardens", ru: "Марвин-Гарденс" },
    group: "yellow",
    price: 280,
    rent: [24, 120, 360, 850, 1025, 1200],
    houseCost: 150,
    mortgage: 140,
  },
  { kind: "goToJail", index: 30, name: { en: "Go To Jail", ru: "В тюрьму!" } },
  {
    kind: "street",
    index: 31,
    name: { en: "Pacific Avenue", ru: "Пасифик-авеню" },
    group: "green",
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgage: 150,
  },
  {
    kind: "street",
    index: 32,
    name: { en: "North Carolina Avenue", ru: "Сев. Каролина" },
    group: "green",
    price: 300,
    rent: [26, 130, 390, 900, 1100, 1275],
    houseCost: 200,
    mortgage: 150,
  },
  { kind: "chest", index: 33, name: { en: "Community Chest", ru: "Казна" } },
  {
    kind: "street",
    index: 34,
    name: { en: "Pennsylvania Avenue", ru: "Пенсильвания-авеню" },
    group: "green",
    price: 320,
    rent: [28, 150, 450, 1000, 1200, 1400],
    houseCost: 200,
    mortgage: 160,
  },
  {
    kind: "railroad",
    index: 35,
    name: { en: "Short Line", ru: "Шорт Лайн" },
    price: 200,
    mortgage: 100,
  },
  { kind: "chance", index: 36, name: { en: "Chance", ru: "Шанс" } },
  {
    kind: "street",
    index: 37,
    name: { en: "Park Place", ru: "Парк-плейс" },
    group: "darkBlue",
    price: 350,
    rent: [35, 175, 500, 1100, 1300, 1500],
    houseCost: 200,
    mortgage: 175,
  },
  { kind: "tax", index: 38, name: { en: "Luxury Tax", ru: "Налог на роскошь" }, amount: 100 },
  {
    kind: "street",
    index: 39,
    name: { en: "Boardwalk", ru: "Бродвок" },
    group: "darkBlue",
    price: 400,
    rent: [50, 200, 600, 1400, 1700, 2000],
    houseCost: 200,
    mortgage: 200,
  },
];

export const STARTING_CASH = 1500;
export const GO_SALARY = 200;
export const JAIL_FINE = 50;
export const JAIL_POSITION = 10;
export const MAX_PLAYERS = 6;
export const MIN_PLAYERS = 2;

export const PLAYER_COLORS = [
  "#ef4444", // red
  "#3b82f6", // blue
  "#22c55e", // green
  "#eab308", // yellow
  "#a855f7", // purple
  "#f97316", // orange
];

export const GROUP_COLORS: Record<string, string> = {
  brown: "#8b5a2b",
  lightBlue: "#7dd3fc",
  pink: "#ec4899",
  orange: "#f97316",
  red: "#dc2626",
  yellow: "#eab308",
  green: "#16a34a",
  darkBlue: "#1d4ed8",
};

/** Сколько клеток одной группы — нужно для проверки монополии. */
export const GROUP_SIZE: Record<string, number> = {
  brown: 2,
  lightBlue: 3,
  pink: 3,
  orange: 3,
  red: 3,
  yellow: 3,
  green: 3,
  darkBlue: 2,
};
